/* THEORY//LAB v0.5 — local, source-anchored reading memory. No network required. */
const corpus=window.CORPUS, $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=s=>s.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'$1 ($2)').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/\*([^*\n]+)\*/g,'$1').replace(/`([^`]+)`/g,'$1').replace(/^#+\s*/gm,'').replace(/^>\s?/gm,'');
const blocks={};for(const d of Object.values(corpus.docs)){blocks[d.id]=d.text.split(/\n\s*\n/).filter(x=>x.trim()&&!/^[-—*]{3,}$/.test(x.trim())).map((s,i)=>({id:String(i),text:plain(s),kind:/^#{1,2}\s/.test(s)?'h2':/^#{3,6}\s/.test(s)?'h3':'p',quote:/^>/.test(s)}));}
let noticeTimer,activeDocs=[],activeReading=null,activeOrigin=null,selectedId=null,pending=null,lastFocus=null;
document.body.insertAdjacentHTML('beforeend','<div id="storageStatus" role="status" aria-live="polite"></div><dialog id="annotationDialog" aria-labelledby="annotationTitle"><form method="dialog" id="annotationForm"><h2 id="annotationTitle">Nota sobre el pasaje</h2><blockquote id="selectedQuote"></blockquote><label for="passageNote">Tu nota (opcional para un subrayado)</label><textarea id="passageNote" placeholder="¿Qué te hace pensar este fragmento?"></textarea><div class="reader-actions"><button type="submit" class="vbtn primary">Guardar</button><button type="button" id="cancelAnnotation" class="vbtn">Cancelar</button></div><p id="annotationError" role="alert"></p></form></dialog>');
function notify(s){$('storageStatus').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('storageStatus').textContent='',5000);}
const storageKey='theorylab_v05_annotations';let annotations=[],storageAvailable=true;
function validNote(a){return a&&typeof a.id==='string'&&typeof a.note==='string'&&typeof a.quote==='string'&&Array.isArray(a.segments)&&a.segments.length&&a.segments.every(s=>typeof s.doc==='string'&&Number.isInteger(s.start)&&Number.isInteger(s.end)&&s.start>=0&&s.end>s.start&&blocks[s.doc]?.[s.block]&&s.end<=blocks[s.doc][s.block].text.length);}
try{const raw=localStorage.getItem(storageKey);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data)||!data.every(validNote))throw Error('invalid');annotations=data;}localStorage.setItem('theorylab_v05_probe','1');localStorage.removeItem('theorylab_v05_probe');}catch(e){storageAvailable=false;document.querySelector('.center').insertAdjacentHTML('afterbegin','<div class="storage-warning" role="alert">No se pudo abrir el almacenamiento local. No se sobrescribirán los datos existentes. Revisa los permisos del navegador para guardar notas.</div>');}
function commit(next){if(!storageAvailable){notify('El almacenamiento local no está disponible. La nota sigue abierta.');return false;}try{localStorage.setItem(storageKey,JSON.stringify(next));annotations=next;return true;}catch(e){notify('No se pudo guardar. El navegador puede estar sin espacio o bloquear el almacenamiento.');return false;}}
const titleMap={means:'La reducción es un medio, no un fin',calm:'Calma y tranquilidad como horizonte abierto',intensify:'Qué se intensifica y para qué',presence:'«Presencia» no basta: ¿presencia de qué?',sensitivity:'Intensificar la sensibilidad, no solo el estímulo',criteria:'Cada reducción implica un criterio',morris:'Morris: un contraste que queda en segundo plano',latency:'Lo que permanece latente'};
document.querySelector('.sub').textContent='v0.5 · memoria de lectura';
document.querySelector('#view-mind .kicker').textContent='MIND · PENSAMIENTOS CON CONTEXTO';
document.querySelector('#view-mind h1').textContent='Volver a la idea completa.';
document.querySelector('#view-mind .hero p').textContent='Tus palabras, las respuestas y las lecturas de las que nacieron. Abre cada conversación para seguir el argumento sin reducirlo a una frase.';
document.querySelector('#view-mind .panel h3').textContent='Ideas y conversaciones';
document.querySelector('#view-readings h1').textContent='Leer, subrayar, volver.';
document.querySelector('#view-readings .hero-main p').textContent='Lecturas recuperadas de «Reducción · sorpresa», con su desarrollo disponible. Selecciona un pasaje para subrayarlo o escribir una nota.';
document.querySelector('.brainmeter').innerHTML='<h4>MEMORIA RECUPERADA</h4><div class="meterrow"><span>Autores</span><b>5</b></div><div class="meterrow"><span>Textos y conversaciones</span><b>'+Object.keys(corpus.docs).length+'</b></div><p class="muted">La vitalidad y la evidencia de v0.4 son valores ilustrativos, no mediciones.</p>';
document.querySelector('.askhint').textContent='Demo heredada de v0.4: respuestas predefinidas sobre un corpus reducido. Sin modelo conectado ni búsqueda externa real.';
document.querySelector('#view-readings .hero-main').insertAdjacentHTML('beforeend','<div class="reader-actions"><button class="vbtn primary" id="allNotes">Ver todos los subrayados y notas</button></div>');
$('allNotes').onclick=()=>openNotebook();
renderThoughts=function(){let list=thoughts.filter(t=>t.tags.includes(state.filter));if(state.filter==='mine')list=thoughts;if(state.filter==='outside')list=[];$('thoughtlist').innerHTML=list.map(t=>{const m=corpus.thoughts[t.id],d=corpus.docs[m.docs[0]],paras=blocks[d.id];let first=paras.slice(0,d.role==='Tus palabras'?Math.min(paras.length,3):4).map(b=>`<p>${esc(b.text)}</p>`).join('');if(d.text.length<700&&m.docs[1]){const response=corpus.docs[m.docs[1]];first+=`<div class="origin-label">${esc(response.role)} · contexto</div>`+blocks[response.id].slice(0,4).map(b=>`<p>${esc(b.text)}</p>`).join('');}return `<article class="thought full ${t.hot==='hot'?'hot':''}"><div class="kicker">${esc(t.kind)} · ${esc(t.status)}</div><h4>${esc(titleMap[t.id])}</h4><div class="origin-label">${esc(d.role)} · ${esc(d.date)}</div>${first}<details><summary>Expandir conversación y contexto completo</summary>${m.docs.map(id=>{const x=corpus.docs[id];return `<div class="origin-label">${esc(x.role)} · ${esc(x.label)} · ${esc(x.date)}</div>${x.partial?'<div class="availability partial">Fragmento recuperado: el final de esta respuesta no está disponible.</div>':''}${blocks[id].map(b=>`<p>${esc(b.text)}</p>`).join('')}<button class="vbtn" data-origin="${id}">Abrir origen y anotar</button>`;}).join('')}</details><div class="origin-actions"><button class="vbtn primary" data-conversation="${t.id}">Abrir conversación</button>${m.readings.map(id=>`<button class="vbtn" data-full-reading="${id}">${esc(readings.find(r=>r.id===id).author)}</button>`).join('')}<button class="vbtn" data-inspect="${t.id}">Mi siguiente pensamiento</button></div></article>`;}).join('')||'<p>Esta vista apunta fuera del corpus. ASK conserva una demostración de exploración externa, sin búsqueda real.</p>';bindContent($('thoughtlist'));};
function bindContent(el){el.querySelectorAll('[data-full-reading]').forEach(b=>b.onclick=()=>openReading(b.dataset.fullReading));el.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>openOrigin([b.dataset.origin],corpus.docs[b.dataset.origin].label));el.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>openOrigin(corpus.thoughts[b.dataset.conversation].docs,titleMap[b.dataset.conversation]));el.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>{selectThought(b.dataset.inspect);$('notearea').focus();});}
renderReadings=function(){$('readinglist').innerHTML=readings.map(r=>{const ds=corpus.readings[r.id],length=ds.reduce((n,id)=>n+corpus.docs[id].text.split(/\s+/).length,0);return `<article class="reading" tabindex="0" role="button" data-full-reading="${r.id}" aria-label="Leer ${esc(r.author)}"><div><div class="who">${esc(r.author)}</div><div class="date">${length.toLocaleString('es')} palabras recuperadas</div></div><div><h4>${esc(corpus.docs[ds[0]].label)}</h4><p>${r.id==='rei'?'Lectura revisada parcial y primera entrega completa.':r.id==='paw'?'Entrega breve original completa. No se recuperó una revisión extensa.':'Desarrollo completo de la lectura disponible en la conversación.'}</p><span class="tag ${r.color}">Abrir lectura y anotaciones</span></div></article>`;}).join('');bindContent($('readinglist'));$('readinglist').querySelectorAll('[role=button]').forEach(el=>el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});};
function sourceHTML(d){return `<div class="doc-header" id="doc-${d.id}"><div class="kicker">${esc(d.role)} · ${esc(d.date)}</div><h2>${esc(d.label)}</h2><a href="chatgpt-conversation://6aa9b6ee-1e58-83eb-a8f5-03f62903c66f">Origen: Reducción · sorpresa</a>${d.partial?'<div class="availability partial">Texto parcial. La copia recuperada se interrumpe al final; se conserva hasta ese punto, sin completar ni inventar el resto.</div>':''}</div>`;}
function decoratedText(doc,b){const relevant=annotations.flatMap(a=>a.segments.filter(s=>s.doc===doc&&String(s.block)===b.id).map(s=>({...s,id:a.id})));const cuts=[...new Set([0,b.text.length,...relevant.flatMap(s=>[s.start,s.end])])].sort((a,b)=>a-b);return cuts.slice(0,-1).map((start,i)=>{const end=cuts[i+1],ids=relevant.filter(s=>s.start<end&&s.end>start).map(s=>s.id),text=esc(b.text.slice(start,end));return ids.length?`<mark data-ids="${esc(ids.join(' '))}" class="${ids.includes(selectedId)?'selected':''}">${text}</mark>`:text;}).join('');}
function renderBody(){const el=$('readerBody');if(!el)return;el.innerHTML=activeDocs.map(id=>sourceHTML(corpus.docs[id])+blocks[id].map(b=>`<${b.kind} data-doc="${id}" data-block="${b.id}" id="passage-${id}-${b.id}" class="${b.quote?'quote-block':''}">${decoratedText(id,b)}</${b.kind}>`).join('')+(corpus.docs[id].partial?'<div class="availability partial">Fin del fragmento disponible. Falta la continuación de esta respuesta.</div>':'')).join('');el.querySelectorAll('mark').forEach(m=>m.onclick=()=>{const id=m.dataset.ids.split(' ')[0];$('note-'+id)?.scrollIntoView({block:'nearest',behavior:'smooth'});selectedId=id;renderNotes();});}
function launchDrawer(){lastFocus=document.activeElement;$('drawer').classList.add('open');$('drawer').setAttribute('role','dialog');$('drawer').setAttribute('aria-modal','true');$('drawer').setAttribute('aria-label','Lectura y memoria');$('app').inert=true;document.documentElement.classList.add('reader-open');$('drawer').scrollTop=0;$('drawerClose').focus();}
function openReader(ids,title,reading=null,origin=null){activeDocs=ids;activeReading=reading;activeOrigin=origin;selectedId=null;pending=null;$('drawerContent').innerHTML=`<div class="kicker">READING MEMORY · v0.5</div><h1>${esc(title)}</h1><div class="availability">Texto recuperado de la conversación. Las lecturas son análisis del asistente; tus intervenciones se identifican por separado. No equivalen al texto íntegro de los libros o ensayos originales. Las referencias internas de ChatGPT no están disponibles; los enlaces escritos en el texto se conservan.</div><div class="reader-grid"><div><div class="reader-toolbar"><button class="vbtn primary" id="highlightSelection">Subrayar selección</button><button class="vbtn" id="noteSelection">Añadir nota</button><button class="vbtn" id="goNotes">Ver anotaciones</button></div><article id="readerBody" class="reader-body"></article></div><aside class="reader-tools" id="readerNotes"></aside></div>`;renderBody();renderNotes();$('highlightSelection').onclick=()=>beginAnnotation(false);$('noteSelection').onclick=()=>beginAnnotation(true);$('goNotes').onclick=()=>$('readerNotes').scrollIntoView({behavior:'smooth'});launchDrawer();}
openReading=function(id){const r=readings.find(x=>x.id===id);if(r)openReader(corpus.readings[id],r.author,id,null);};
function openOrigin(ids,title){openReader(ids,title,null,{ids,title});}
function captureSelection(){const selection=getSelection();if(!selection.rangeCount||selection.isCollapsed)return null;const range=selection.getRangeAt(0),container=$('readerBody');if(!container||!container.contains(range.startContainer)||!container.contains(range.endContainer))return null;const segments=[];for(const p of container.querySelectorAll('[data-block]')){if(!range.intersectsNode(p))continue;const part=document.createRange();part.selectNodeContents(p);if(p.contains(range.startContainer))part.setStart(range.startContainer,range.startOffset);if(p.contains(range.endContainer))part.setEnd(range.endContainer,range.endOffset);if(part.collapsed)continue;const prefix=document.createRange();prefix.selectNodeContents(p);prefix.setEnd(part.startContainer,part.startOffset);const start=prefix.toString().length,end=start+part.toString().length;if(end>start)segments.push({doc:p.dataset.doc,block:p.dataset.block,start,end});}if(!segments.length)return null;return {segments,quote:segments.map(s=>blocks[s.doc][s.block].text.slice(s.start,s.end)).join('\n\n')};}
document.addEventListener('selectionchange',()=>{const s=captureSelection();if(s)pending=s;});
for(const event of ['pointerup','keyup'])document.addEventListener(event,e=>{if($('readerBody')?.contains(e.target)){const s=captureSelection();pending=s;}});
function beginAnnotation(withNote){const selection=captureSelection()||pending;if(!selection){notify('Selecciona primero un fragmento dentro de la lectura.');return;}const a={id:globalThis.crypto?.randomUUID?.()||'a'+Date.now()+Math.random().toString(16).slice(2),...selection,note:'',created:new Date().toISOString(),reading:activeReading,origin:activeOrigin};if(withNote){editAnnotation(a,true);return;}if(commit([...annotations,a])){selectedId=a.id;pending=null;getSelection().removeAllRanges();renderBody();renderNotes();notify('Subrayado guardado en este navegador.');}}
let draft=null,isNew=false;
function editAnnotation(a,newNote=false){draft=a;isNew=newNote;$('selectedQuote').textContent=a.quote;$('passageNote').value=a.note;$('annotationTitle').textContent=newNote?'Nota sobre el pasaje':'Editar nota';$('annotationError').textContent='';$('annotationDialog').showModal();$('passageNote').focus();}
$('cancelAnnotation').onclick=()=>$('annotationDialog').close();
$('annotationForm').onsubmit=e=>{e.preventDefault();const a={...draft,note:$('passageNote').value,updated:new Date().toISOString()};if(!commit(isNew?[...annotations,a]:annotations.map(x=>x.id===a.id?a:x))){$('annotationError').textContent='La nota no se ha guardado. El texto permanece aquí para que puedas copiarlo.';return;}$('annotationDialog').close();pending=null;selectedId=a.id;getSelection().removeAllRanges();renderBody();renderNotes();notify('Nota y subrayado guardados.');};
function noteCards(list){return list.map(a=>`<section class="note-card" id="note-${esc(a.id)}"><small>${esc(corpus.docs[a.segments[0].doc].label)} · ${new Date(a.created).toLocaleDateString('es')}</small><blockquote>${esc(a.quote)}</blockquote><p>${a.note?esc(a.note):'<span class="muted">Subrayado sin nota</span>'}</p><div class="note-actions"><button class="vbtn" data-jump="${esc(a.id)}">Ir al fragmento</button><button class="vbtn" data-edit="${esc(a.id)}">${a.note?'Editar nota':'Añadir nota'}</button><button class="vbtn" data-delete="${esc(a.id)}">Eliminar</button></div></section>`).join('');}
function bindNotes(el){el.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jumpTo(b.dataset.jump));el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAnnotation(annotations.find(a=>a.id===b.dataset.edit)));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const a=annotations.find(a=>a.id===b.dataset.delete);if(confirm('¿Eliminar este subrayado y su nota?')&&commit(annotations.filter(x=>x.id!==a.id))){renderBody();renderNotes();notify('Anotación eliminada.');}});}
function renderNotes(){const el=$('readerNotes');if(!el){if($('notebookList'))renderNotebook();return;}const list=annotations.filter(a=>a.segments.some(s=>activeDocs.includes(s.doc)));el.innerHTML=`<h2>Subrayados y notas <span class="note-count">${list.length}</span></h2><p>Selecciona un pasaje y usa «Subrayar selección» o «Añadir nota». Se guardan en este navegador.</p>${noteCards(list)||'<p class="muted">Todavía no hay anotaciones en esta lectura.</p>'}`;bindNotes(el);}
function jumpTo(id){const a=annotations.find(x=>x.id===id);if(!a)return;const s=a.segments[0];if(!$('readerBody')||!activeDocs.includes(s.doc)){if(a.reading)openReading(a.reading);else openOrigin(a.origin?.ids||[s.doc],a.origin?.title||corpus.docs[s.doc].label);}selectedId=id;renderBody();renderNotes();const p=$('passage-'+s.doc+'-'+s.block);p.classList.add('passage-focus');p.tabIndex=-1;p.focus({preventScroll:true});p.scrollIntoView({block:'center',behavior:'smooth'});}
function openNotebook(){activeDocs=[];activeReading=null;$('drawerContent').innerHTML='<div class="kicker">MEMORIA LOCAL</div><h1>Subrayados y notas</h1><p class="muted">Todas tus anotaciones, con acceso directo al pasaje de origen.</p><div id="notebookList"></div>';renderNotebook();launchDrawer();}
function renderNotebook(){$('notebookList').innerHTML=noteCards(annotations)||'<p class="muted">Todavía no hay anotaciones. Abre una lectura y selecciona un pasaje para empezar.</p>';bindNotes($('notebookList'));}
function closeReader(){$('drawer').classList.remove('open');$('app').inert=false;document.documentElement.classList.remove('reader-open');pending=null;lastFocus?.isConnected&&lastFocus.focus();}
$('drawerClose').textContent='Cerrar';$('drawerClose').onclick=closeReader;
document.addEventListener('keydown',e=>{if(!$('drawer').classList.contains('open')||$('annotationDialog').open)return;if(e.key==='Escape')closeReader();if(e.key==='Tab'){const list=[...$('drawer').querySelectorAll('button,a[href],textarea,[tabindex="0"]')].filter(x=>x.getClientRects().length);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
$('saveNote').onclick=()=>{try{const next={...savedNotes,[state.selected]:$('notearea').value};localStorage.setItem('theorylab_v04_notes',JSON.stringify(next));Object.assign(savedNotes,next);$('saved').textContent='Guardado en este navegador.';$('saved').classList.add('show');}catch{notify('No se pudo guardar. Copia tu texto antes de cerrar.');}};
window.addEventListener('storage',e=>{if(e.key!==storageKey)return;try{const data=JSON.parse(e.newValue||'[]');if(Array.isArray(data)&&data.every(validNote)){annotations=data;renderBody();renderNotes();}}catch{notify('No se pudo leer un cambio de otra pestaña.');}});
renderThoughts();renderReadings();
